[package]
name = "mindful"
version = "1.0.0"
authors = []

[addresses]
message_board_addr = "_"

[dependencies]
AptosFramework = { local = "/home/jim/aptos-core-main/aptos-move/framework/aptos-framework", rev = "testnet" }
AptosTokenObjects = { local = "/home/jim/aptos-core-main/aptos-move/framework/aptos-token-objects", rev = "testnet" }

[dev-dependencies]
