[package]
name = "mindful"
version = "1.0.0"
authors = []

[addresses]
module_add = "0x222268ac20a4e051781c0b6bfedd13432880dd69ddb750b169be4b2650c8d395"

[dependencies]
AptosFramework = { local = "/home/jim/aptos-core-main/aptos-move/framework/aptos-framework", rev = "testnet" }
AptosTokenObjects = { local = "/home/jim/aptos-core-main/aptos-move/framework/aptos-token-objects", rev = "testnet" }

[dev-dependencies]
